name: Deploy to Dev

on:
  workflow_dispatch:   # allow manual/API triggers
    inputs:
      jiraIssueKey:
        description: "Triggered from Jira"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploy triggered from Jira issue: ${{ github.event.inputs.jiraIssueKey }}"
          # your deployment steps here
